### ISSUE TITLE
Impossible to install it

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/custom_meta#3]
I try to install it to Backdrop 1.3.4 and got this:

_Cannot determine the type of project._

**Comment by klonos** [comment]
@bd0bd you can either wait for a new official release of the module that included the change that fixes this, or you can simply add the following line to the custom_meta
.info file:

`type = module`

**Comment by bd0bd** [comment]
Thank you!

**Comment by klonos** [comment]
You're welcome. Actually, lets keep the issue open until the module developer commits the change and creates a new release that includes the fix.
